openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: User API

paths:
  /users:
    get:
      summary: Get all users
      operationId: getAllUsers
      responses:
        '200':
          description: Return 0 or more user objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        500:
          description: Some sort of server issue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserErrorResponse'
  /users/{id}:
    get:
      summary: Get a user by ID
      operationId: getUserById
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      summary: Update a user by ID
      operationId: updateUserById
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      summary: Delete a user by ID
      operationId: deleteUserById
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '204':
          description: User deleted successfully

components:
  schemas:
    User:
      type: object
      allOf:
        - $ref: '#/components/schemas/UserBase'
      properties:
        id:
          type: string
        address:
          $ref: '#/components/schemas/Address'
    UserInput:
      allOf:
        - $ref: '#/components/schemas/UserBase'
        - type: object
          properties:
            password:
              type: string
    UserBase:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
    Address:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        state:
          type: string
    UserResponse:
      anyOf:
        - $ref: '#/components/schemas/User'
        - type: object
          properties:
            message:
              type: string
    UserErrorResponse:
      oneOf:
        - $ref: '#/components/schemas/User'
        - type: object
          properties:
            error:
              type: string

  parameters:
    UserId:
      name: id
      in: path
      description: User ID
      required: true
      schema:
        type: string

  examples:
    UserExample:
      value:
        id: "1"
        name: John Doe
        email: john.doe@example.com
        address:
          street: 123 Main St
          city: Anytown
          state: CA
    ErrorResponseExample:
      value:
        error: An error occurred.

  responses:
    UserResponse:
      description: User response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserResponse'
          examples:
            userExample:
              $ref: '#/components/examples/UserExample'
    ErrorResponse:
      description: Error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserErrorResponse'
          examples:
            errorExample:
              $ref: '#/components/examples/ErrorResponseExample'